version: '2'
services:
  jose:
      build: .
      depends_on:
          - mongo
          - postgres
      volumes:
          - ./:/jose
  josecoin:
      build: ./jcoin
      depends_on:
          - postgres
      volumes:
          - ./jcoin/:/jcoin
      ports:
          - "8080:8080"

  mongo:
      image: "mongo:3.6-jessie"
      volumes:
          - ./data/mongo:/data/db
  postgres:
      image: "postgres:10.1"
      volumes:
          - ./data/postgres:/var/lib/postgresql/data
          - ./jcoin/schema.sql:/docker-entrypoint-initdb.d/schema.sql
