# Phrases that will be shown randomly when jose starts
JOSE_PLAYING_PHRASES = [
    'I Sexually Identify as an Attack Helicopter',
    'Memes',
    'Discord > Skype',
    'I\'d love to make profit',
    'Features coming Soon™',
    'Use Python 3.x, please',
    'What are you doing in my swamp™',
    '7 GRAND DAD?!?',
    'The game who nobody asks about',
    'Nice meme\'d mister.',
    '2 2 2',
    'with myself',
    'nothing',
    'with destiny',
    'with your feelings'
    'I wanna be the bot',
    'and TASing chess',
    'with humans',
    'playing',
    '4chan',
    'Imgur',
    'Reddit',
    'Sentience™',
    'Favela in Brazil',
    'Politics',
    'I\'ve seen it on tumblr',
    'Expand Dong',
    'Bonzi Buddy',
    'Debugging',
    'Databases',
    'Guitar',
    '♬ Blank Banshee',
    'KSP',
    'with your heart',
    'Dance Dance Revolution',
    'PRANKS ON YOU BRO',
    'Really Makes Me Think™',
    'Black Mirror',
    'Netflix',
    'Bot Dev Tycoon',
    'Hell',
    'Overwatch',
    'Poker with Satan',
    'Anime',
    'TV',
    'Communism',
    'Capitalism',
    'Philosophy with IBM Watson',
    'Skynet 2.0',
    '♬ Daft Punk',
    'YouTube',
    'Westworld with Dolores',
    '♬ Saint Pepsi',
    'with bots, my only friends',
    'NSFW Fanfics',
    'my keyboard layout keeps changing',
    'Linux',
    'Apple fanboys',
    '♬ Lady GaGa',
    '♬ Burzum',
    'CSI: NY',
    '♬ Michael Jackson',
    'Bazinga',
    'Yiff',
    'Club Penguin',
    'Club Penguin Server Administration',
    'Big Tyrone Simulator',
    '♬ MACINTOSH PLUS - リサフランク420 / 現代のコンピュー',
    '♬ TANUKI - BABYBABYの夢',
    '♬ ナイトNaito - Talk About Love',
    '♬ 悲しい Android - Apartment - Your Love',
    '♬ BALENTSバランス - 植物と動物',
    '♬ Metallica - Master of Puppets',
    '♬ Information Flash - Early In The Mornin\'',
    '♬ Night Tempo & ミカヅキBIGWAVE - Loveパズル',
    '♬ Compilerbau - Fragments Of Bach I',
    '♬ Burzum - Dunkelheit',
    '♬ Aphex Twin - Rhubarb',
    '♬ Lady Gaga - Love Game',
    '♬ ECCO2K - GT-R',
    '♬ Mayhem - Deathcrush',
    '♬ Vond - Selvmord',
    '♬ Venom - Buried Alive',
    '♬ Darkthrone - Transilvanian Hunger',
    '♬ Marcel Everett - The Dead Farmer',
    '♬ Marcel Everett - Stay Inside',
    '♬ We Are Number One',
    'h3h3productions',
]
